### ISSUE TITLE
v4 Overview for devs who would like to contribute

### ISSUE THREAD

**Issue by shady-ti** [spotDL/spotdl-v4#1]
### Requested Feature

I'd like to contribute but without a general overview, I'm not sure where to start.

### Possible implementation

Talk me through the overview/your plans and I'll write up some an Overview.md (?)

**Comment by xnetcat** [comment]
Utils - contains commonly used functions and functions

Types - types used in spotdl project

Providers - contains different providers used to do specific tasks like downloading/searching songs, finding songs. New providers use base class to make creating new providers easier

Progress handlers - this needs to be reworked

Download - download manager

Console - contains different operations like download, preload and web. This is where everything starts

__init__ - contains spotdl class that simplifies the download process

Tbh it's not that different from V3, I've just added new features, fixed bugs and made the code better. 

The only things left to do are tests and docs (bugs if find any 😜)

**Comment by shady-ti** [comment]
I'll do the docs.

**Comment by shady-ti** [comment]
> Console - contains different operations like download, preload and web. This is where everything starts

what does preload do? I assume web = web-ui

**Comment by xnetcat** [comment]
> what does preload do? I assume web = web-ui

It works like `save` but it also searches for the youtube url and saves it

> what's the difference between types and init

which `init`

**Comment by shady-ti** [comment]
> which `init`

the sub-package
