### ISSUE TITLE
Skipping Songs

### ISSUE THREAD

**Issue by bobz5460** [spotDL/spotdl-v4#19]
### System OS

Windows

### Python Version

3.9 (CPython)

### Install Source

pip / PyPi

### Install version / commit hash

4.0.0

### Expected Behavior vs Actual Behavior

It was supposed to download a 424 song playlist, but only downloaded 398, some saying "skipping [whatever song it is]", even though I'm running it in a blank folder.

### Steps to reproduce

spotdl download https://open.spotify.com/playlist/14eqoG7VqXnC1BMLjRD9XI?si=7a5b04583ca14ff4

### Traceback

```text
none
```

### Other details

[Spotdl Commandline.txt](https://github.com/spotDL/spotdl-v4/files/8791677/Spotdl.Commandline.txt)
That is what spotdl did in CMD, music folder was empty at the start of the command.

**Comment by xnetcat** [comment]
It's skipping songs because there are duplicates in your playlist (post Malone - sunflower for example). I will check the missing songs later

**Comment by bobz5460** [comment]
Oh, ok I did not notice that. I thought Spotify would auto remove duplicates in a playlist or something. Thanks for the help.
